name: Publicar site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  construir:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v6

      - name: Configurar Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          

      - name: Instalar dependências
        run: npm install

      - name: Criar o site
        run: npm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Enviar site
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  publicar:
    needs: construir
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Publicar site
        id: publicar
        uses: actions/deploy-pages@v4
