name: Publicar site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  construir:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.6.12

      - name: Instalar dependências
        run: pnpm install

      - name: Criar site
        run: pnpm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Enviar site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  publicar:
    needs: construir
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Publicar
        id: deployment
        uses: actions/deploy-pages@v4
